Optimize the container initialization process.

diff --git a/root/etc/cont-init.d/18-rclone b/root/etc/cont-init.d/18-rclone
--- a/root/etc/cont-init.d/18-rclone
+++ b/root/etc/cont-init.d/18-rclone
@@ -21,18 +21,21 @@ INFO="[${Green_font_prefix}INFO${Font_color_suffix}]"
 ERROR="[${Red_font_prefix}ERROR${Font_color_suffix}]"
 
 if [ "$RCLONE" = "enable" ]; then
-    echo -e "${INFO} Installation RCLONE ..."
+    echo; echo -e "${INFO} Installation RCLONE ..."
     apk add -q --no-cache unzip
     curl -fsSL https://rclone.org/install.sh | bash
-    [ ! -e /config/rclone/rclone.conf ] && {
-        mkdir -p /config/rclone
-        touch /config/rclone/rclone.conf
+    cd /config
+    [ ! -e rclone/rclone.conf ] && {
+        mkdir -p rclone
+        touch rclone/rclone.conf
     }
-    while [ ! -e /config/autoupload.sh ]; do
-        echo -e "${INFO} Doanload 'autoupload.sh' ..."
-        curl -fsSL https://raw.githubusercontent.com/P3TERX/aria2.conf/master/autoupload.sh -o /config/autoupload.sh
-        [ ! -e /config/autoupload.sh ] \
-            && echo -e "${ERROR} 'autoupload.sh' doanload error, retry ..."
-        sleep 5
+    while [ ! -e autoupload.sh ]; do
+        echo; echo -e "${INFO} Doanload 'autoupload.sh' ..."
+        curl -fsSLO https://raw.githubusercontent.com/P3TERX/aria2.conf/master/autoupload.sh || \
+        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/autoupload.sh
+        [ -e autoupload.sh ] || {
+            echo; echo -e "${ERROR} 'autoupload.sh' doanload error, retry ..."
+            sleep 5
+        }
     done
 fi
